# Generated by Django 3.2.16 on 2023-01-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20221129_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='new_post',
            field=models.BooleanField(default=True),
        ),
    ]
