# Generated by Django 3.2.16 on 2023-02-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_new_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog_post',
            field=models.BooleanField(default=True),
        ),
    ]
