# Generated by Django 3.2.16 on 2023-02-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_blog_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_post',
            field=models.BooleanField(default=False),
        ),
    ]
