# Generated by Django 3.2.16 on 2023-03-15 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0010_conversations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversations',
            name='author',
        ),
        migrations.RemoveField(
            model_name='conversations',
            name='recipients',
        ),
        migrations.RemoveField(
            model_name='direct_message',
            name='marked_as_new',
        ),
        migrations.RemoveField(
            model_name='direct_message',
            name='new_messages',
        ),
        migrations.RemoveField(
            model_name='direct_message',
            name='recipient',
        ),
        migrations.AddField(
            model_name='conversations',
            name='marked_as_new',
            field=models.ManyToManyField(related_name='marked_as_new', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversations',
            name='recipient',
            field=models.ManyToManyField(related_name='recipient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='direct_message',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.conversations'),
        ),
        migrations.DeleteModel(
            name='Reply_Message',
        ),
    ]
