# Generated by Django 3.2.16 on 2023-03-03 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_pollq_pollv2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollq',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pollq', to='polls.pollv2'),
        ),
    ]
